[package]
name = "reed"
version = "0.1.0"
authors = ["Simon Dickson <simonhdickson@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
futures = "0.3"
http = "0.2"
hyper = { version = "0.13", features = ["stream"] }
lazy_static = "1.4"
prost = "0.6"
prost-derive = "0.6"
prost-types = "0.6"
rustls-native-certs = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["rt-core", "macros", "stream"] }
tokio-rustls = "0.12"
tonic = { version = "0.1", features = ["tls", "tls-roots"] }
webpki-roots = "0.18"

rdkafka = { version = "0.23", features = ["cmake-build"] }

[build-dependencies]
tonic-build = "0.1"

[dev-dependencies]
env_logger = "0.7"
